version: '3'

services:
  core:
    container_name: core
    build:
      context: core
    image: core:latest
    ports:
      - "8081:8081"
    depends_on:
      - core-db
    volumes:
      - ./core/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./core/src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql

  league-table:
    container_name: league-table
    build:
      context: league-table
    image: league-table:latest
    ports:
      - "8083:8083"
    environment:
      core.url: http://core:8081/
    depends_on:
      - core

  game-scheduler:
    container_name: game-scheduler
    build:
      context: game-scheduler
    image: game-scheduler:latest
    environment:
      core.url: http://core:8081/
    ports:
      - "8082:8082"
    depends_on:
      - core

  model:
    container_name: model
    build:
      context: model
    image: model:latest

  core-db:
    image: postgres:15.2-alpine
    container_name: core-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  client:
    container_name: client
    build:
      context: client
    image: client:latest
    environment:
      core.url: http://core:8081
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml:Z"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    volumes:
      - "./grafana/provisioning/dashboards/dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json"
      - "./grafana/provisioning/dashboards/grafana-dashboard.yml:/etc/grafana/provisioning/dashboards/grafana-dashboard.yml"
      - "./grafana/provisioning/datasources/prometheus-ds.yml:/etc/grafana/provisioning/datasources/prometheus-ds.yml"
    ports:
      - "3000:3000"
    environment:
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: "/etc/grafana/provisioning/dashboards/dashboard.json"



