{
 "title": "Home",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"core\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - disk_free_bytes{job=\"core\"} / disk_total_bytes * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "system_cpu_usage" }
   ]
  },
  {
   "title": "Scrape durations",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "scrape_duration_seconds" }
   ]
  }
 ]
}